using IVDClient.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Threading;

namespace IVDClient
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public IVDServerCurrentState cs;

        private FileSystemWatcher IVDCurrentStateJSONWatcher;
        private string lastJSONFilePath = "";

        public MainWindow()
        {
            InitializeComponent();

            IVDCurrentStateJSONWatcher = new FileSystemWatcher(@"C:\Games\Transport Fever 2");
            IVDCurrentStateJSONWatcher.NotifyFilter = NotifyFilters.LastWrite;
            IVDCurrentStateJSONWatcher.Filter = "*.json";
            IVDCurrentStateJSONWatcher.IncludeSubdirectories = true;
            IVDCurrentStateJSONWatcher.Changed += new FileSystemEventHandler(OnIVDCurrentStateJSONChanged);
            IVDCurrentStateJSONWatcher.EnableRaisingEvents = true;

            //ProcessUpdatedJSON(@"C:\Games\Transport Fever 2\ivdCurrentState_0.json");
            //UpdateUI();
        }

        private void OnIVDCurrentStateJSONChanged(object sender, FileSystemEventArgs e)
        {
            Console.WriteLine($"Changed: {e.FullPath}");
            if (lastJSONFilePath != "")
            {
                ProcessUpdatedJSON(lastJSONFilePath);
                this.Dispatcher.BeginInvoke(() => { UpdateUI(); });
            }
            lastJSONFilePath = e.FullPath; //We're doing this to prevent file access conflicts, cycling between multiple JSON files generated by the Transport Fever 2 IVD mod
        }

        private void ProcessUpdatedJSON(string path)
        {
            using (var fileStream = new FileStream(lastJSONFilePath, FileMode.Open, FileAccess.Read))
                cs = JsonSerializer.Deserialize<IVDServerCurrentState>(fileStream);
            IVDCurrentStateJSONWatcher.EnableRaisingEvents = false; //We're making it so it only imports the data once to improve performance
        }

        private void UpdateUI()
        {
            VehiclesDataGrid.ItemsSource = GenerateDataGridContent();
        }

        private List<HomePageDataGridVehicle> GenerateDataGridContent()
        {
            var vehicles = new List<HomePageDataGridVehicle>();

            foreach (var vehicle in cs.vehicles)
            {
                var v = new HomePageDataGridVehicle()
                {
                    id = vehicle.id,
                    name = vehicle.name,
                    lineID = vehicle.line
                };
                if (v.lineID != -1) //Making sure it's not a depot
                    v.lineName = cs.lines.FirstOrDefault(l => l.id == vehicle.line).name;
                else
                    v.lineName = "DEPOT";
                vehicles.Add(v);
            }

            return vehicles.OrderBy(c => c.name.Length).ThenBy(c => c.name).ToList();
        }

        private void VehiclesDataGrid_MouseDoubleClick(object sender, System.Windows.Input.MouseButtonEventArgs e)
        {
            var selectedVehicle = (HomePageDataGridVehicle)VehiclesDataGrid.SelectedItem;
            if (selectedVehicle.lineID != -1) //Making sure it's not a depot
            {
                var vdw = new VehicleDisplayWindow(selectedVehicle.id);
                vdw.Show();
            }
        }

        // This is so the columns get their name from the model attributes
        private void OnAutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            var displayName = GetPropertyDisplayName(e.PropertyDescriptor);

            if (!string.IsNullOrEmpty(displayName))
            {
                e.Column.Header = displayName;
            }
        }

        public static string GetPropertyDisplayName(object descriptor)
        {
            var pd = descriptor as PropertyDescriptor;

            if (pd != null)
            {
                // Check for DisplayName attribute and set the column header accordingly
                var displayName = pd.Attributes[typeof(DisplayNameAttribute)] as DisplayNameAttribute;

                if (displayName != null && displayName != DisplayNameAttribute.Default)
                {
                    return displayName.DisplayName;
                }
            }
            else
            {
                var pi = descriptor as PropertyInfo;

                if (pi != null)
                {
                    // Check for DisplayName attribute and set the column header accordingly
                    Object[] attributes = pi.GetCustomAttributes(typeof(DisplayNameAttribute), true);
                    for (int i = 0; i < attributes.Length; ++i)
                    {
                        var displayName = attributes[i] as DisplayNameAttribute;
                        if (displayName != null && displayName != DisplayNameAttribute.Default)
                        {
                            return displayName.DisplayName;
                        }
                    }
                }
            }

            return null;
        }
    }
}